# Generated by Django 2.2.19 on 2022-05-21 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='input title here', max_length=150, verbose_name='title of group')),
                ('slug', models.SlugField(help_text='input a unique url-name of group', unique=True, verbose_name='slug of group')),
                ('description', models.TextField(help_text='input a description here', max_length=150, verbose_name='Brief description of the item group')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name_of_items')),
                ('description', models.TextField(max_length=250, verbose_name='descr of item')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='img', verbose_name='photo_item')),
                ('price', models.PositiveIntegerField(verbose_name='price')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='a date of created')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item', to='shop.Group', verbose_name='group of items')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(fields=('name',), name='item'),
        ),
    ]
