# Generated by Django 2.2.19 on 2022-05-21 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='collection',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='collection_of_items'),
        ),
    ]
