# Generated by Django 2.2.19 on 2022-05-22 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20220522_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='collection',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='name_of_items'),
        ),
        migrations.DeleteModel(
            name='Collection',
        ),
    ]
