# Generated by Django 2.2.19 on 2022-05-22 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20220522_2018'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите сюда имя группы', max_length=200, verbose_name='Name of collection: ')),
                ('slug', models.SlugField(help_text='Уникальный адрес группы: ', unique=True, verbose_name='uniq url of the collection ')),
                ('description', models.TextField(help_text='Введите краткое описание группы', verbose_name='descriptions of collection')),
            ],
        ),
        migrations.AlterField(
            model_name='item',
            name='collection',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='collection'),
        ),
    ]
