# Generated by Django 2.2.19 on 2022-05-22 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20220522_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='old_price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='item',
            name='collection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item', to='shop.Collection', verbose_name='collections of items'),
        ),
    ]
