# Generated by Django 2.2.19 on 2022-05-23 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20220522_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='old_price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='old_price'),
        ),
    ]
