# Generated by Django 2.2.19 on 2022-05-25 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_auto_20220523_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='img', verbose_name='photo_item'),
        ),
        migrations.AddField(
            model_name='item',
            name='values',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default=1, max_length=50, verbose_name='name_of_items'),
            preserve_default=False,
        ),
    ]
