# Generated by Django 2.2.19 on 2022-05-23 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0013_auto_20220523_1833'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='input name', max_length=150, verbose_name='title of group')),
                ('second_name', models.CharField(max_length=150)),
                ('middle_name', models.CharField(max_length=150)),
                ('country', models.CharField(max_length=150)),
                ('region', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=150)),
                ('street', models.CharField(max_length=150)),
                ('house', models.CharField(max_length=150)),
                ('flat', models.CharField(max_length=150)),
                ('orders', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='user.User', verbose_name='item in ordering')),
                ('itemcart', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item', to='shop.Item', verbose_name='item in ordering')),
            ],
        ),
    ]
